import { TimerManager } from '@src/timer_manager.ts'
import Util from '@src/utilt.ts'
import { UtpAddr } from '@src/utp_addr.ts'
import { UtpConn, UtpConnState } from '@src/utp_conn.ts'
import { UTPListener } from '@src/utp_listener.ts'
import { UtpPacket, UtpPacketType } from '@src/utp_packet.ts'
import { assert } from 'std/assert/assert.ts'
import { Logger } from '@src/logger.ts'
import { UtpContext } from '@src/utp_context.ts'

export enum UtpState {
  ACTIVE,
  CLOSE_WAIT,
  CLOSED
}

export class Utp {
  static DEFAULT_MTU = 1400 // deno not support mtu discovery, so use a default value
  #udpSocket!: Deno.DatagramConn
  #TIMEOUT_CHECK_TIMER_NAME = `UTP_TIMEOUT_CHECK_TIMER_${crypto.randomUUID()}`
  #TIMEOUT_CHECK_INTERVAL = 300 // ms
  listener: UTPListener
  listening: boolean
  #connTable: Map<string, UtpConn>
  #state: UtpState
  #totalBytesWritten: number
  #totalBytesRead: number
  #totalUdpPacketSent: number
  #totalUdpPacketReceived: number
  #utpPacketReceived: number
  #mockPacketLossRate: number
  #mockPacketLossEnabled: boolean
  #tag: string
  logger: Logger

  constructor(tag: string = '') {
    this.#tag = tag
    UtpContext.getInstance().setListenerType(this.#tag)
    // 使用Context获取Logger实例
    this.logger = UtpContext.getInstance().getLogger('UTP_SOCKET')

    this.listening = false
    this.listener = new UTPListener()
    this.#state = UtpState.ACTIVE
    this.#connTable = new Map()
    this.#totalBytesWritten = 0
    this.#totalBytesRead = 0
    this.#totalUdpPacketSent = 0
    this.#totalUdpPacketReceived = 0
    this.#utpPacketReceived = 0
    this.#mockPacketLossRate = 0.01
    this.#mockPacketLossEnabled = false
  }

  // 启用日志
  enableLogging(): void {
    this.logger.enable()
  }

  // 禁用日志
  disableLogging(): void {
    this.logger.disable()
  }

  get localAddr(): UtpAddr | undefined {
    return this.#udpSocket?.addr ? UtpAddr.fromDenoAddr(this.#udpSocket.addr as Deno.Addr) : undefined
  }

  /**
   * @param addr local address to listen on
   */
  private createUdpSocketIfNone(addr?: UtpAddr) {
    if (this.#udpSocket) {
      return
    }

    // after listen function called, the listenAddr will be set
    if (addr) {
      this.#udpSocket = Deno.listenDatagram({
        port: addr.port,
        hostname: addr.hostname,
        transport: 'udp'
      })
    }
    // after connect function called, the listenAddr will be set
    else {
      this.#udpSocket = Deno.listenDatagram({
        port: 0,
        hostname: '0.0.0.0',
        transport: 'udp'
      })
    }

    const localAddr = UtpAddr.fromDenoAddr(this.#udpSocket.addr as Deno.Addr)

    this.logger.info(`μTP socket is listening on ${localAddr.toString()}`)

    this.startListen()
    this.startTimeoutCheck()
  }

  /**
   * create a new connection to the peer, and execute the SYN command
   * @param remoteAddr
   * @returns
   */
  async connect({ port, hostname }: { port: number; hostname: string }): Promise<UtpConn> {
    this.createUdpSocketIfNone()

    const remoteAddr = new UtpAddr(port, hostname)
    this.logger.info(`Attempting to connect to ${remoteAddr.hostname}:${remoteAddr.port}`)

    // the send id and recv id should be generated by the sender
    const localRecvId = Util.randomUn16Int()
    const localSendId = localRecvId + 1
    const seqNr = 1
    const ackNr = 0

    return await UtpConn.connectTo(this, UtpConnState.CS_SYN_SENT, remoteAddr, localSendId, localRecvId, seqNr, ackNr)
  }

  /**
   * create a μTP server
   * @param options listen options,if not provided, a random port will be used, and listen on all interfaces
   */
  listen({ port, hostname = '0.0.0.0' }: { port: number; hostname?: string }): UTPListener {
    this.createUdpSocketIfNone(new UtpAddr(port, hostname))
    return this.listener
  }

  /**
   * close the UTP listener and all connections
   */
  close(): Promise<void> {
    if (this.#state === UtpState.CLOSED) {
      this.logger.debug('The UTP socket is already closed')
      return Promise.resolve()
    }

    if (this.#state === UtpState.CLOSE_WAIT) {
      this.logger.debug('The UTP socket is in CLOSE_WAIT state, waiting for the connections to close')
      return Promise.resolve()
    }

    this.#state = UtpState.CLOSE_WAIT

    this.logger.info(`Closing UTP listener on ${this.localAddr?.hostname}:${this.localAddr?.port}`)
    // close lisetenr
    this.listener.close()

    // close all connections and wait for the close to complete
    const tryCloseSocket = () => {
      if (this.connSize() === 0) {
        this.stopTimeoutCheck()
        this.#udpSocket.close()
        this.#state = UtpState.CLOSED
        this.logger.info('UTP socket closed')
        return true
      } else {
        const conns = Array.from(this.#connTable.values())
        const canCloseConns = conns.filter(
          (conn) => conn.localState !== UtpConnState.CS_CLOSE_WAIT && conn.localState !== UtpConnState.CS_CLOSED
        )

        for (const conn of canCloseConns) {
          this.logger.debug(`Closing connection with ID: ${conn.uniqueId()}`)
          conn.close()
        }
        return false
      }
    }

    // 等待所有连接关闭：先立即尝试，若还有连接则轮询
    if (tryCloseSocket()) return Promise.resolve()

    return new Promise<void>((resolve) => {
      const checkInterval = setInterval(() => {
        if (tryCloseSocket()) {
          clearInterval(checkInterval)
          resolve()
        }
      }, 1000)
    })
  }

  printConnTableKeys(): void {
    const keys = Array.from(this.#connTable.keys())
    this.logger.debug(`Connection table keys: ${keys.length > 0 ? keys.join(', ') : 'None'}`)
  }

  addConn(conn: UtpConn): void {
    this.logger.info(`Adding new connection with ID: ${conn.uniqueId()}`)
    this.#connTable.set(conn.uniqueId(), conn)
  }

  removeCon(conn: UtpConn): void {
    this.logger.info(`Removing connection with ID: ${conn.uniqueId()}`)
    this.#connTable.delete(conn.uniqueId())
  }

  findConn(uniqueId: string): UtpConn | undefined {
    return this.#connTable.get(uniqueId)
  }

  hasConn(uniqueId: string): boolean {
    return this.#connTable.has(uniqueId)
  }

  connSize(): number {
    return this.#connTable.size
  }

  async timeoutCheck(): Promise<void> {
    // iterate all connections
    for (const conn of this.#connTable.values()) {
      if (![UtpConnState.CS_CLOSED, UtpConnState.CS_RESET].includes(conn.localState)) {
        await conn.timeoutCheck()
      }
    }
  }

  startTimeoutCheck(): void {
    this.logger.debug(`Starting timeout check timer`)
    TimerManager.setTimer(this.#TIMEOUT_CHECK_TIMER_NAME, this.timeoutCheck.bind(this), this.#TIMEOUT_CHECK_INTERVAL)
  }

  stopTimeoutCheck(): void {
    this.logger.debug(`Stopping timeout check timer`)
    TimerManager.clearTimer(this.#TIMEOUT_CHECK_TIMER_NAME)
  }

  async startListen(): Promise<void> {
    this.logger.info(`Starting to listen for incoming UTP packets`)
    while (!this.isClosed()) {
      try {
        // DENO BUG:超过1024字节的UDP数据包会被截断,手动调整缓冲区大小为默认MTU的2倍
        const [udpBytes, remoteAddr] = await this.#udpSocket.receive(new Uint8Array(Utp.DEFAULT_MTU * 2))

        // mock packet loss,if enabled,drop the packet
        if (this.#mockPacketLossEnabled && Math.random() < this.#mockPacketLossRate) {
          continue
        }

        this.#totalUdpPacketReceived++
        this.#totalBytesRead += udpBytes.length
        await this.dispatch(udpBytes, remoteAddr)
      } catch (err) {
        if (!this.isClosed()) {
          throw err
        } else {
          this.logger.debug('UDP socket is closed')
        }
      }
    }
  }

  isClosed(): boolean {
    return this.#state === UtpState.CLOSED
  }

  isCloseWait(): boolean {
    return this.#state === UtpState.CLOSE_WAIT
  }

  isActive(): boolean {
    return this.#state === UtpState.ACTIVE
  }

  /**
   * send utp packet to remote address
   * @param outgoingPacket
   * @returns
   */
  async sendUtpPacket(outgoingPacket: UtpPacket, remoteAddr: UtpAddr): Promise<number> {
    if (this.isClosed()) {
      this.logger.debug('The UTP socket is closed, cannot send packet')
      return 0
    }

    this.logger.debug(
      `=======> UDP: 发送UDP数据包到${remoteAddr.toString()},seq is ${outgoingPacket.seqNr},ack is ${outgoingPacket.ackNr
      }`
    )
    const bytes = outgoingPacket.toBytes()
    this.#totalBytesWritten += bytes.length
    this.#totalUdpPacketSent++

    const n = await this.#udpSocket.send(bytes, {
      port: remoteAddr.port,
      hostname: remoteAddr.hostname,
      transport: 'udp'
    })

    assert(n === bytes.length, 'UDP:发送的数据包长度与实际发送的数据包长度不一致')

    return n
  }

  /**
   * dispatch the incoming packet to the corresponding handler
   * @param udpBytes
   * @param remoteUdpAddr
   */
  async dispatch(udpBytes: Uint8Array, remoteUdpAddr: Deno.Addr): Promise<void> {
    if (!UtpPacket.isPacket(udpBytes)) {
      this.logger.debug(`invalid utp packet from ${remoteUdpAddr}`)
      return
    }

    // 解析数据包
    const packet = UtpPacket.fromBytes(udpBytes)
    const remoteAddr = UtpAddr.fromDenoAddr(remoteUdpAddr)

    this.logger.debug(`<======= Receiving packet from ${remoteAddr.toString()} to the target connection`)
    this.logger.debug(packet.toString())

    this.#utpPacketReceived++

    if (packet.type === UtpPacketType.ST_SYN) {
      this.logger.debug('received a SYN packet from', remoteAddr)

      // create a new connection
      // only when type is SYN, the connId means sendId
      const remoteRecvId = packet.connId
      const remoteSendId = packet.connId + 1

      const localSendId = remoteRecvId
      const localRecvId = remoteSendId

      const targetUniqueId = UtpConn.generateUniqueId(remoteAddr, localSendId, localRecvId)

      if (this.hasConn(targetUniqueId)) {
        this.logger.debug(`connection already exists for the packet from ${remoteAddr}`)
        // TODO resepone with a RST packet or ignore the packet, avoid to create a duplicate connection
        return
      }

      const seqNr = Util.randomUn16Int()
      const ackNr = packet.seqNr
      const conn = UtpConn.connectTo(this, UtpConnState.CS_SYN_RECV, remoteAddr, localSendId, localRecvId, seqNr, ackNr)
      // notify the listener to accept a new connection; swallow rejection (e.g. 5s SYN_RECV timeout)
      conn.then(conn => this.listener.addConnection(conn)).catch(err => this.logger.debug(`SYN_RECV connection failed: ${err}`))
    } else {
      // we don't know the sender of the packet is initiator or responder
      // but we know initiator's sendId is the same as responder's recvId,and initiator's recvId is the same as responder's sendId
      // and we also know the when type is not SYN, the connId means remote sendId
      // so localRecvId = remoteSendId
      // because we don't know the sender is initiator or responder，so there are 2 possibilities
      // localSendId = localRecvId + 1 or localSendId = localRecvId - 1
      const localRecvId = packet.connId
      const localSendIds = [localRecvId + 1, localRecvId - 1]
      const targetConns = localSendIds
        .map((sendId) => UtpConn.generateUniqueId(remoteAddr, sendId, localRecvId))
        .map((uniqueId) => this.findConn(uniqueId))
        .filter((conn) => conn !== undefined) as UtpConn[]

      // if no connection found, ignore the packet
      if (targetConns.length === 0) {
        this.logger.debug(`No connection found for the packet from ${remoteAddr}`)
        return
      }

      // handle the packet
      for (const conn of targetConns) {
        if (packet.type === UtpPacketType.ST_RESET) {
          conn.reset()
        } else {
          const handled = await conn.handleIncomingPacket({
            packet,
            remoteAddr
          })

          if (handled) {
            break
          }
        }
      }
    }
  }
}
